name: Build and tests

on:
  # Ignore changes in extra plugins (as they are not tested here)
  push:
    paths-ignore:
      - 'extra_plugins/**'
  pull_request:
    paths-ignore:
      - 'extra_plugins/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - 'ubuntu:22.04'

    name: Build on ${{ matrix.image }}
    container: ${{ matrix.image }}
    steps:

    # Dependencies ---------------------------------------------------------------------------
    - name: Install dependencies for libfds and IPFIXcol2 (Ubuntu)
      run: |
        apt-get update
        apt-get -y install git gcc g++ cmake make libxml2-dev liblz4-dev libzstd-dev
        apt-get -y install python3-docutils zlib1g-dev pkg-config
        apt-get -y install librdkafka-dev doxygen
      env:
        DEBIAN_FRONTEND: noninteractive

    # Checkout repository --------------------------------------------------------------------
    - uses: actions/checkout@v2

    # Build libfds library  ------------------------------------------------------------------
    # Note: Master against master branch. Otherwise against debug branch.
    - name: Checkout libfds library - master branch
      if: github.ref == 'refs/heads/master'
      run: git clone --branch master https://github.com/CESNET/libfds.git libfds_build
    - name: Checkout libfds library - devel branch
      if: github.ref != 'refs/heads/master'
      run: git clone --branch devel https://github.com/CESNET/libfds.git libfds_build
    - name: Build and install libfds library
      working-directory: libfds_build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr
        make && make install

    # Build and test IPFIXcol2 ---------------------------------------------------------------
    - name: Build and install IPFIXcol2
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=1
        make && make install
    - name: Try to run IPFIXcol2
      run: |
        ipfixcol2 -V
        ipfixcol2 -h
        ipfixcol2 -L -v
