name: Build DEB packages

on:
  push:
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deb:
    # Build DEB packages on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ['ubuntu:22.04']

    name: Build DEBs on ${{ matrix.image }}
    container: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v2
    - name: Define variables
      uses: actions/github-script@v5
      with:
        script: |
          const sha = context.sha.substring(0, 8);
          const image = `${{ matrix.image }}`
          const distro = image.split('/').pop().replace(/:/g,'_');
          const zip = `ipfixcol2-${distro}-${sha}`;
          core.exportVariable('ZIP_FILE', zip);
    - name: Prepare environment
      run: |
        mkdir -p build/libfds_repo

    # Dependencies ---------------------------------------------------------------------------
    - name: Install dependencies for libfds and IPFIXcol2 (Ubuntu)
      run: |
        apt-get update
        apt-get -y install git gcc g++ cmake make libxml2-dev liblz4-dev libzstd-dev libmicrohttpd12 libmicrohttpd-dev
        apt-get -y install python3-docutils zlib1g-dev pkg-config librdkafka-dev
        apt-get -y install debhelper devscripts build-essential fakeroot zip doxygen
      env:
        DEBIAN_FRONTEND: noninteractive

    # Build LIBFDS DEB package ---------------------------------------------------------------
    - name: Checkout libfds library - master branch
      if: github.ref == 'refs/heads/master'
      run: git clone --branch master https://github.com/CESNET/libfds.git build/libfds_repo
    - name: Checkout libfds library - devel branch
      if: github.ref != 'refs/heads/master'
      run: git clone --branch devel https://github.com/CESNET/libfds.git build/libfds_repo
    - name: Build DEBs of libfds library and install them
      working-directory: 'build/libfds_repo'
      run: |
        mkdir build && cd build
        cmake .. -DPACKAGE_BUILDER_DEB=On -DCPACK_PACKAGE_CONTACT="GitHub actions <no-reply@example.com>"
        make deb
        apt -y install ./pkg/deb/debbuild/libfds*.deb

    # Build IPFIXcol2 DEB package ------------------------------------------------------------
    - name: Build IPFIXcol2 DEBs and install them
      run: |
        cd build
        cmake .. -DPACKAGE_BUILDER_DEB=On -DCPACK_PACKAGE_CONTACT="GitHub actions <no-reply@example.com>"
        make deb
        apt -y install ./pkg/deb/debbuild/*.deb
    - name: List generated DEB artifacts
      run: |
        ls -al build/pkg/deb/debbuild || true
    - name: Archive DEB packages
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ZIP_FILE }}
        path: |
          build/pkg/deb/debbuild/*.deb
          build/pkg/deb/debbuild/*.ddeb
          build/pkg/deb/debbuild/*.tar.gz
          build/pkg/deb/debbuild/*.dsc
    - name: Publish DEBs to GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/pkg/deb/debbuild/*.deb
          build/pkg/deb/debbuild/*.ddeb
          build/pkg/deb/debbuild/*.tar.gz
          build/pkg/deb/debbuild/*.dsc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 